### ISSUE TITLE
Definir site do projeto

### ISSUE THREAD

**Issue by gabrielbpn** [Interacao-Humano-Computador/2020.2-Vjudge#1]
Precisamos selecionar um site para o projeto da disciplina.

**Comment by italovinicius18** [comment]
Discutimos entre o grupo e decidimos trabalhar com o site **Vjudge**, por ter uma interface que podemos trabalhar, já que somos alunos de software temos mais contato, auxiliando o nosso desenvolvimento como programadores, verificando se condiz com seu objetivo e assim verificaremos se é uma boa solução de IHC
